set(REQUIREDS "")

function(component_register)
    set(options SHARED REQUIRED)
    set(one_value_args COMPONENT_NAME)
    set(multi_value_args SRCS INCLUDE_DIRS PRIVATE_INCLUDE_DIRS REQUIREDS PRIVATE_REQUIREDS LIBRARY_DIRS COMPILE_OPTIONS PRIVATE_COMPILE_OPTIONS COMPILE_DEFINITIONS PRIVATE_COMPILE_DEFINITIONS)

    cmake_parse_arguments(COMPONENT_REGISTER "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

    message(STATUS "Registering component ${COMPONENT_REGISTER_COMPONENT_NAME}")
    
    # option(ENABLE_${COMPONENT_REGISTER_COMPONENT_NAME} "Enable ${COMPONENT_REGISTER_COMPONENT_NAME}" OFF)
        
    # if(NOT ENABLE_${COMPONENT_REGISTER_COMPONENT_NAME})
    #     return()
    # endif()

    # message(STATUS "Enable ${COMPONENT_REGISTER_COMPONENT_NAME} ON")

    foreach(lib_dir IN LISTS COMPONENT_REGISTER_LIBRARY_DIRS)
        message(STATUS "Linking ${lib_dir}")
        link_directories(${lib_dir})
    endforeach()
    
    foreach(inc IN LISTS COMPONENT_REGISTER_INCLUDE_DIRS)
        include_directories(${inc})
    endforeach()


    if(DEFINED COMPONENT_REGISTER_SRCS)
        if(COMPONENT_REGISTER_SHARED)
            add_library(${COMPONENT_REGISTER_COMPONENT_NAME} SHARED ${COMPONENT_REGISTER_SRCS})
            install(TARGETS ${COMPONENT_REGISTER_COMPONENT_NAME} DESTINATION ${CMAKE_BINARY_DIR}/lib)
        else()
            add_library(${COMPONENT_REGISTER_COMPONENT_NAME} STATIC ${COMPONENT_REGISTER_SRCS})
        endif()

        target_include_directories(${COMPONENT_REGISTER_COMPONENT_NAME} PRIVATE ${COMPONENT_REGISTER_PRIVATE_INCLUDE_DIRS})
        target_link_libraries(${COMPONENT_REGISTER_COMPONENT_NAME} PUBLIC ${COMPONENT_REGISTER_REQUIREDS})
        target_link_libraries(${COMPONENT_REGISTER_COMPONENT_NAME} PRIVATE ${COMPONENT_REGISTER_PRIVATE_REQUIREDS})

        # Add compile options
        if(COMPONENT_REGISTER_COMPILE_OPTIONS)
            target_compile_options(${COMPONENT_REGISTER_COMPONENT_NAME} PUBLIC ${COMPONENT_REGISTER_COMPILE_OPTIONS})
        endif()

        if(COMPONENT_REGISTER_PRIVATE_COMPILE_OPTIONS)
            target_compile_options(${COMPONENT_REGISTER_COMPONENT_NAME} PRIVATE ${COMPONENT_REGISTER_PRIVATE_COMPILE_OPTIONS})
        endif()

        # Add compile definitions
        if(COMPONENT_REGISTER_COMPILE_DEFINITIONS)
            target_compile_definitions(${COMPONENT_REGISTER_COMPONENT_NAME} PUBLIC ${COMPONENT_REGISTER_COMPILE_DEFINITIONS})
        endif()

        if(COMPONENT_REGISTER_PRIVATE_COMPILE_DEFINITIONS)
            target_compile_definitions(${COMPONENT_REGISTER_COMPONENT_NAME} PRIVATE ${COMPONENT_REGISTER_PRIVATE_COMPILE_DEFINITIONS})
        endif()

        list(APPEND REQUIREDS ${COMPONENT_REGISTER_PRIVATE_REQUIREDS})
    endif()

    if(COMPONENT_REGISTER_REQUIREDS)
        list(APPEND REQUIREDS ${COMPONENT_REGISTER_REQUIREDS})
    endif()

    if(COMPONENT_REGISTER_REQUIRED)
        list(APPEND REQUIREDS ${COMPONENT_REGISTER_COMPONENT_NAME})
    endif()

    set(REQUIREDS ${REQUIREDS} PARENT_SCOPE)

endfunction()
